### PR TITLE
Support "today" and "yesterday" (as well as uppercase versions) for date range of anti_samp - Iss112

### PR DESCRIPTION
**Pull request by j450h1**
Support "today" and "yesterday" (as well as uppercase versions) for date range of anti_sample

### CODE REVIEW

**Comment by MarkEdmondson1234** [comment]
This is great thanks.  I can see how it would be easy to add "5daysAgo" , "7daysAgo" calls as well using this method.   Please also feel free to add your name to the contributors in DESCRIPTION and a NEWS entry.

**Comment by j450h1** [comment]
No problem. Sure, will do. Regarding NEWS, should this go under the latest version - googleAnalytics 0.4.1.9000?

**Comment by MarkEdmondson1234** [comment]
> Regarding NEWS, should this go under the latest version - googleAnalytics 0.4.1.9000?

Yep

**Comment by j450h1** [comment]
Sounds good. Let me know if you need me to make any other adjustments.

**Pull request merged**
