### PR TITLE
Re: Warn if using metrics in dimension filters and vice versa #68

### PR DESCRIPTION
**Pull request by j450h1**
Let me know if you have any feedback. Thanks!

### CODE REVIEW

**Comment by MarkEdmondson1234** [comment]
Thanks you!  But you don't need to import all the dimensions/metrics as they are in the package already in the `meta` table which has a helper function here:

https://github.com/MarkEdmondson1234/googleAnalyticsR/blob/ff89a7b08148c781b1ab62e3603e7ced4bdf68bf/R/custom_dims_mets.R#L14-L54

For this application I guess use the non call the metadata API version:

```r
allowed_metric_dim("METRIC", callAPI = FALSE)
```

**Comment by j450h1** [comment]
suggest a better error message if its too colloquial or badly phrased.

```
# dimension
df <- dim_filter("bounces","BEGINS_WITH","1",not = TRUE)
#>Error: Oops..looks like you have used a metric in a dimension filter!
# typo
df <- dim_filter("sources","BEGINS_WITH","1",not = TRUE)
#>Error: Oops...looks like you've entered an invalid metric filter name!

# metric
mf <- met_filter("source", "GREATER_THAN", 0)
#>Error: Oops..looks like you have used a dimension in a metric filter!

# typo
mf <- met_filter("bounce", "GREATER_THAN", 0)
#>Error: Oops...looks like you've entered an invalid metric filter name!
```

**Comment by MarkEdmondson1234** [comment]
Thanks you @j450h1 - sorry it took so long to merge, in my defence I've moved house since :)

**Comment by j450h1** [comment]
@MarkEdmondson1234 no worries! Was a bit confused, but now I'll look into something else I can help with.

**Pull request merged**
