### PR TITLE
Fix the auto anti sample math

### PR DESCRIPTION
**Pull request by olivia-icivics**
Chunks are now computed to not exceed 250k session per chunk. This is experimentally when Google Analytics starts to sample. This should fix, or at least greatly mitigate, issue #70.

Previously, the math would use the result of the integer division of the cumulative sum of the sessions to determine the chunks. This had the side effect of not guaranteeing staying under any limit.

For example, if the date range we are interested in starts with a 99k day, followed by 200k days, the first day would be alone (as it should), but the next two would be grouped together into a 400k day, whereas they should all be in their own batch.
```

1.  99k, cumulative=99,  batch=99k/250k+1=1
2. 200k, cumulative=299, batch=299k/250k+1=2
3. 200k, cumulative=499, batch=499k/250k+1=2

```

The new code uses a simple accumulator loop to guarantee requests stay under 250k.

---

Note: I do not understand why we are using `read_counts` when the sampling thresholds are purely based on the session numbers. I might be missing the bigger picture here, but this works whereas `read_counts` does not.

Note2: this 250k is currently hard coded, but should probably move up to the session itself. This could have a nice benefit for those who might be interested in controlling sampling. I can easily see how setting it to, for example, 1M, could allow to neatly control the sample rate for every day in the range.

### CODE REVIEW

**Comment by MarkEdmondson1234** [comment]
Very cool, thanks for this, and doh over my maths.

However the 250k limit I think will be an issue for GA360 accounts?  They have a larger sampling space.  There is also some features on v4 that may effect this figure in the future.  This was the main reason to rely on what the API returns as read_counts, IIRC.  Does this still work when being used in your fork?

**Comment by olivia-icivics** [comment]
Right, so that's when we'd want to start moving this to a function argument.

My impression of `read_counts` (on Standard) is that it's maxes out just below 500k sessions, which makes sense given `samplingLevel=LARGE`. However, it's only once I go under 250k sessions that there is no sampling. So maybe `read_counts/2` is the way to go?

And yes, the code works like a charm in my fork :)

**Comment by MarkEdmondson1234** [comment]
Ok working local tests so I'm merging for the wider public to also test, although will reverse if anything pops up :)  Thank you!  Please also add yourself as a contributor to the DESCRIPTION :)

**Comment by MarkEdmondson1234** [comment]
Oh and a line in the NEWS file

**Pull request merged**
